ShopComp/Controllers/OrderDetailsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopComp.Data;
using ShopComp.Models;
using ShopComp.Services;
using System.Collections.Generic;
using System.Linq;

namespace ShopComp.Controllers
{
    public class OrderDetailsController : Controller
    {
        AppDBContent db;
        private UserManager<User> _userManager;
        IWebHostEnvironment _appEnvironment;
        EmailService emailService = new();
        FileService fileService = new();
        OrderDetails orderDetails;
        List<Cart> carts;

        public OrderDetailsController(UserManager<User> userManager, AppDBContent context, IWebHostEnvironment appEnvironment)
        {
            _userManager = userManager;
            db = context;
            _appEnvironment = appEnvironment;
        }

        public IActionResult ConfirmOrders() => View(db.OrderDetails.Include(u => u.Users).ToList().Where(p => !p.Submitted && !p.Cancel && !p.Condition));

        public IActionResult SentOrders() => View(db.OrderDetails.Include(u => u.Users).ToList().Where(p => p.Submitted && !p.Cancel && !p.Condition));

        public IActionResult CompletedOrder() => View(db.OrderDetails.Include(u => u.Users).ToList().Where(p => p.Submitted && p.Condition));

        [HttpPost]
        public IActionResult ConfirmReceiptOrder(int id)
        {
            orderDetails = db.OrderDetails.Where(p => p.Id == id).FirstOrDefault();
            orderDetails.Condition = true;
            carts = db.Carts.Include(p => p.Tovar).Where(p => p.OrderDetailsID == id && p.Status).ToList();
            db.OrderDetails.Update(orderDetails);
            carts.ForEach(p => p.Condition = true);
            carts.ForEach(p => p.Tovar.Sold += p.Quantity);
            db.SaveChanges();
            return View();
        }

        [HttpPost]
        public IActionResult SentReview(OrderDetails model)
        {
            orderDetails = db.OrderDetails.Where(p => p.Id == model.Id).FirstOrDefault();
            orderDetails.Review = model.Review;
            db.OrderDetails.Update(orderDetails);
            db.SaveChanges();
            return RedirectToAction("ListOrder", "Cart");
        }

        [HttpPost]
        public IActionResult CancelOrder(int id)
        {
            orderDetails = db.OrderDetails.Where(p => p.Id == id).FirstOrDefault();
            orderDetails.Cancel = true;
            orderDetails.Condition = true;
            carts = db.Carts.Include(p => p.Tovar).Where(p => p.OrderDetailsID == id && p.Status).ToList();
            carts.ForEach(m => m.Tovar.Amount += m.Quantity);
            db.OrderDetails.Update(orderDetails);
            db.Carts.RemoveRange(carts);
            db.SaveChanges();
            return View();
        }

        [HttpPost]
        public IActionResult DeleteOrder(int? id)
        {
            orderDetails = db.OrderDetails.Find(id);
            db.OrderDetails.Remove(orderDetails);
            db.Carts.RemoveRange(db.Carts.Where(p => p.OrderDetailsID == id && p.Status && p.Condition));
            db.SaveChanges();
            return RedirectToAction("SentOrders");
        }

        [HttpPost]
        public IActionResult ConfirmSentOrder(int? id)
        {
            orderDetails = db.OrderDetails.Include(p => p.Users).Where(p => p.Id == id).FirstOrDefault();
            orderDetails.Submitted = true;
            carts = db.Carts.Include(x => x.Tovar).Where(p => p.OrderDetailsID == id && p.Status).ToList();
            carts.ForEach(m => m.Submitted = true);
            db.OrderDetails.Update(orderDetails);
            emailService.SendEmailAsync(orderDetails.Users.Email, "Заказ отправлен",
            $"<h2>Заказ № {orderDetails.Id}</h2><h4>Ваша посылка была отправлена. Ориентировочное время доставки 3 дня.</h4>");
            db.SaveChanges();
            return RedirectToAction("ConfirmOrders");
        }

        [HttpGet]
        public ActionResult MoreDetails(int? id)
        {
            if (id == null)
                return NotFound("Страница не найдена");
            orderDetails = db.OrderDetails.Include(p => p.Users).Where(p => p.Id == id).FirstOrDefault();
            ViewBag.User = orderDetails.Users.Name + " " + orderDetails.Users.Surname + " " + orderDetails.Users.Patronymic;
            ViewBag.Phone = orderDetails.Phone;
            ViewBag.Country = orderDetails.Country;
            ViewBag.CreditCard = orderDetails.CreditCard;
            ViewBag.Line1 = orderDetails.Line1;
            ViewBag.Line2 = orderDetails.Line2;
            ViewBag.GiftWrap = orderDetails.GiftWrap;
            ViewBag.Submitted = orderDetails.Submitted;
            ViewBag.Condition = orderDetails.Condition;
            carts = db.Carts.Include(x => x.Tovar).Include(x => x.Tovar.Categories).Where(p => p.OrderDetailsID == id && p.Status).ToList();
            if (carts != null)
                return View(carts);
            return NotFound("Страница не найдена");
        }


    }
}

ShopComp/Controllers/TovarsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopComp.Data;
using ShopComp.Models;
using ShopComp.ViewModels;
using ShopComp.ViewModels.Pages;
using ShopComp.ViewModels.Tovars;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopComp.Controllers
{
    public class TovarsController : Controller
    {
        AppDBContent db;
        Tovar tovar;

        public TovarsController(AppDBContent context)
        {
            db = context;
        }

        public async Task<IActionResult> ListTovars(SortState sortOrder = SortState.TittleAsc)
        {
            IQueryable<Tovar> tovars = db.Tovars.Include(u => u.Categories);
            ViewData["TittleSort"] = sortOrder == SortState.TittleAsc ? SortState.TittleDesc : SortState.TittleAsc;
            ViewData["CategorySort"] = sortOrder == SortState.CategoryAsc ? SortState.CategoryDesc : SortState.CategoryAsc;
            ViewData["ColSort"] = sortOrder == SortState.ColAsc ? SortState.ColDesc : SortState.ColAsc;
            ViewData["PriceSort"] = sortOrder == SortState.PriceAsc ? SortState.PriceDesc : SortState.PriceAsc;
            tovars = sortOrder switch
            {
                SortState.TittleDesc => tovars.OrderByDescending(s => s.Tittle),
                SortState.ColAsc => tovars.OrderBy(s => s.Amount),
                SortState.ColDesc => tovars.OrderByDescending(s => s.Amount),
                SortState.PriceAsc => tovars.OrderBy(s => s.Price),
                SortState.PriceDesc => tovars.OrderByDescending(s => s.Price),
                SortState.CategoryAsc => tovars.OrderBy(s => s.Categories.Tittle),
                SortState.CategoryDesc => tovars.OrderByDescending(s => s.Categories.Tittle),
                _ => tovars.OrderBy(s => s.Tittle),
            };
            return View(await tovars.AsNoTracking().ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> List(int? category, string name, int minPrice, int sort = 1, int page = 1, int maxPrice = 100000)
        {
            int pageSize = 4;
            IQueryable<Tovar> tovars = db.Tovars.Include(p => p.Categories);
            if (category != null && category != 0)
                tovars = tovars.Where(p => p.CategoriesId == category);
            if (sort != 0)
                if (sort == 1)
                    tovars = tovars.OrderBy(p => p.Price);
                else if (sort == 2)
                    tovars = tovars.OrderByDescending(p => p.Price);
                else if (sort == 3)
                    tovars = tovars.OrderByDescending(p => p.Sold);
            if (minPrice != 0 || maxPrice != 0)
                tovars = tovars.Where(p => p.Price >= minPrice && p.Price <= maxPrice);
            if (!String.IsNullOrEmpty(name))
                tovars = tovars.Where(p => p.Tittle.Contains(name));
            List<Category> categories = db.Categories.ToList();
            categories.Insert(0, new Category { Tittle = "Все", Id = 0 });
            var count = await tovars.CountAsync();
            var items = await tovars.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
            IndexViewModel viewModel = new()
            {
                PageViewModel = new PageViewModel(count, page, pageSize),
                FilterViewModel = new FilterViewModel(db.Categories.ToList(), category, name),
                Tovars = items
            };
            ViewBag.Name = name;
            ViewBag.Sort = sort;
            ViewBag.MinPrice = minPrice;
            ViewBag.MaxPrice = maxPrice;
            if (category != null)
            {
                ViewBag.Category = db.Categories.ToList().Where(p => p.Id != category && !p.Status);
                ViewBag.CategoryTittle = db.Categories.ToList().Where(p => p.Id == category && !p.Status);
            }
            else ViewBag.Category = db.Categories.ToList().Where(p => !p.Status);
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Index() => View();

        [HttpGet]
        public IActionResult AddTovar() => View(db.Categories.ToList().Where(p => !p.Status));

        [HttpPost]
        public IActionResult AddTovar(Tovar order)
        {
            db.Tovars.Add(order);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> EditTovar(int? id)
        {
            if (id != null)
            {
                tovar = await db.Tovars.FirstOrDefaultAsync(p => p.Id == id);
                if (tovar != null)
                    ViewBag.Category = db.Categories.ToList().Where(p => p.Id != tovar.CategoriesId && !p.Status);
                ViewBag.CategoryTittle = db.Categories.ToList().Where(p => p.Id == tovar.CategoriesId && !p.Status);
                return View(tovar);
            }
            return NotFound("Страница не найдена");
        }

        [HttpPost]
        public ActionResult EditTovar(Tovar tovar)
        {
            db.Tovars.Update(tovar);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult MoreDetails(int? id)
        {
            if (id == null)
                return NotFound("Страница не найдена");
            tovar = db.Tovars.Find(id);
            ViewBag.CategoryTittle = db.Categories.Where(p => p.Id == tovar.CategoriesId && !p.Status);
            if (tovar != null)
                return View(tovar);
            return NotFound("Страница не найдена");
        }

        [HttpPost]
        public ActionResult DeleteTovar(int? id)
        {
            Cart cart = db.Carts.Where(p => p.Tovar.Id == id).FirstOrDefault();
            if (cart != null)
                db.Remove(cart);
            tovar = db.Tovars
                .FirstOrDefault(c => c.Id == id);
            if (tovar != null)
                db.Tovars.Remove(tovar);
            db.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

ShopComp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Carousel.by</title>
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- Bootstrap CSS (jsDelivr CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="your_website_domain/css_root/flaticon.css">
    <!-- Bootstrap Bundle JS (jsDelivr CDN) -->
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <a class="navbar-brand" asp-controller="Tovars" asp-action="List">Carousel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                @if (ViewContext.HttpContext.User.IsInRole("admin") || ViewContext.HttpContext.User.IsInRole("user"))
                {
                    <div class="dropdown">
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false"> <img src="~/img/user.png" alt="Alternate Text" /></button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item" href="~/Account/EditUser">Изменить</a></li>
                            <li>
                                <form method="post" asp-controller="Account" asp-action="LogOff">
                                    <button class="dropdown-item">Выйти</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <form method="get" asp-controller="Account" asp-action="Login">
                        <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Войти" />
                    </form>

                }
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link " asp-controller="Tovars" asp-action="List">Каталог</a>
                </li>
                @if (ViewContext.HttpContext.User.IsInRole("user"))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Cart" asp-action="Index">Корзина</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Cart" asp-action="ListOrder">Заказы</a>
                    </li>
                }
                @if (ViewContext.HttpContext.User.IsInRole("admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Index">Пользователи</a>
                    </li>
                    <li class="dropdown">
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                            Просмотреть
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item" asp-controller="Tovars" asp-action="ListTovars">Товары</a></li>
                            <li><a class="dropdown-item" asp-controller="Category" asp-action="ListCategory">Категории</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                            Заказы
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item" asp-controller="OrderDetails" asp-action="ConfirmOrders">Оформленные</a></li>
                            <li><a class="dropdown-item" asp-controller="OrderDetails" asp-action="SentOrders">Отправленные</a></li>
                            <li><a class="dropdown-item" asp-controller="OrderDetails" asp-action="CompletedOrder">История</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                            Добавить
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item" asp-controller="Tovars" asp-action="AddTovar">Товар</a></li>
                            <li><a class="dropdown-item" asp-controller="Category" asp-action="AddCategory">Категорию</a></li>
                        </ul>
                    </li>
                }
            </ul>
            </div>
        </nav>
    </header>
    @RenderBody()
    <footer class="text-center text-lg-start bg-light text-muted">
        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
            <div class="me-5 d-none d-lg-block">
                <h4 class="lead">Следи за нами в социальных сетях:</h4>
            </div>
            <div>
                <a href="https://vk.com/thelidren" target="_blank" class="m-4 text-reset">
                    <img src="~/img/vk.png" alt="" />
                </a>
                <a href="https://vk.com/away.php?to=https%3A%2F%2Finstagram.com%2Faleksandrbondarev266%3Futm_medium%3Dcopy_link&cc_key=" target="_blank" class="m-4 text-reset">
                    <img src="~/img/instagram.png" alt="" />
                </a>
                <a href="https://www.youtube.com/channel/UCZMCeefvl74zHKg4hKQCLKg" target="_blank" class="m-4 text-reset">
                    <img src="~/img/youtube.png" alt="" />
                </a>
            </div>
        </section>
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <div class="row mt-3">
                    <div class="col-md-5 col-lg-6 col-xl-5 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i>О нас
                        </h6>
                        <p>
                            Наш интернет-магазин специализируется в сфере продажи компьютерной техники и переферии.
                        </p>
                        <p>
                            Сетевое издание «Carousel.by». Свидетельство о государственной регистрации средства массовой информации №16 от 26.06.2019 выдано Министерством информации Республики Беларусь.
                        </p>
                        <p>
                            Главный редактор — Мисевич Владислав Александрович.
                        </p>
                    </div>
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">
                            Полезные ссылки
                        </h6>
                        <p>
                            <a asp-controller="Tovars" asp-action="List" class="text-reset">Товары</a>
                        </p>
                        <p>
                            <a asp-controller="Cart" asp-action="Index" class="text-reset">Корзина</a>
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">
                            Контакты
                        </h6>
                        <p><i class="fas fa-home me-3"></i> г. Гомель ул. Речицкая 4</p>
                        <p>
                            <i class="fas fa-envelope me-3"></i>
                            the_lidrenvlamis@mail.ru
                        </p>
                        <p><i class="fas fa-phone me-3"></i>375 25 610 73 30</p>
                        <p><i class="fas fa-print me-3"></i>375 23 232 00 06</p>
                    </div>
                </div>
            </div>
        </section>
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2021 Авторские права:
            <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
    </footer>
</body>
</html>

ShopComp/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Carousel.by</title>
    <link href="~/css/footer.css" rel="stylesheet" />
    <!-- Bootstrap CSS (jsDelivr CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <!-- Bootstrap Bundle JS (jsDelivr CDN) -->
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <a class="navbar-brand" asp-controller="Tovars" asp-action="List">Carousel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                @if (ViewContext.HttpContext.User.IsInRole("admin") || ViewContext.HttpContext.User.IsInRole("user"))
                {
                    <div class="dropdown">
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false"> <img src="~/img/user.png" alt="Alternate Text" /></button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item" href="~/Account/EditUser">Изменить</a></li>
                            <li>
                                <form method="post" asp-controller="Account" asp-action="LogOff">
                                    <button class="dropdown-item">Выйти</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <form method="get" asp-controller="Account" asp-action="Login">
                        <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Войти" />
                    </form>

                }
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link " asp-controller="Tovars" asp-action="List">Каталог</a>
                    </li>
                    @if (ViewContext.HttpContext.User.IsInRole("user"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Cart" asp-action="Index">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Cart" asp-action="ListOrder">Заказы</a>
                        </li>
                    }
                    @if (ViewContext.HttpContext.User.IsInRole("admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Index">Пользователи</a>
                        </li>
                        <li class="dropdown">
                            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                Просмотреть
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li><a class="dropdown-item" asp-controller="Tovars" asp-action="ListTovars">Товары</a></li>
                                <li><a class="dropdown-item" asp-controller="Category" asp-action="ListCategory">Категории</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                Заказы
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li><a class="dropdown-item" asp-controller="OrderDetails" asp-action="ConfirmOrders">Оформленные</a></li>
                                <li><a class="dropdown-item" asp-controller="OrderDetails" asp-action="SentOrders">Отправленные</a></li>
                                <li><a class="dropdown-item" asp-controller="OrderDetails" asp-action="CompletedOrder">История</a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                Добавить
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li><a class="dropdown-item" asp-controller="Tovars" asp-action="AddTovar">Товар</a></li>
                                <li><a class="dropdown-item" asp-controller="Category" asp-action="AddCategory">Категорию</a></li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    @RenderBody()
</body>
</html>